server:
  port: 1205
  servlet:
    context-path: "/ems"

spring:
  datasource:
    url: "jdbc:mysql://localhost"
    username: "root"
    password: "root"

  sql:
    init:
      mode: ALWAYS

  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


